[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mantle_mainnet = "https://rpc.mantle.xyz"
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"
localhost = "http://127.0.0.1:8545"

[etherscan]
mantle_mainnet = { key = "${MANTLESCAN_API_KEY}", url = "https://api.mantlescan.xyz/api" }
mantle_sepolia = { key = "${MANTLESCAN_API_KEY}", url = "https://api-sepolia.mantlescan.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
